# Generated by Django 5.0 on 2023-12-23 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('des', models.TextField(blank=True, null=True)),
                ('dell', models.CharField(blank=True, max_length=30, null=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.main_category')),
                ('price1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.price')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sub_category')),
            ],
        ),
    ]
