# Generated by Django 5.0 on 2023-12-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img1',
            new_name='img',
        ),
    ]
