# Generated by Django 5.0 on 2023-12-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_img1_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dell',
        ),
    ]
