# Generated by Django 5.0 on 2023-12-26 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_name_category_name1_product_name1'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('price', models.IntegerField()),
                ('t_price', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(max_length=30)),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
