# Generated by Django 5.0 on 2024-01-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_addcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
