# Generated by Django 5.0 on 2024-01-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_billing_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_address',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
    ]
