# Generated by Django 5.0 on 2024-01-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_billing_address_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=40, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('qtn', models.IntegerField()),
                ('product_total', models.IntegerField()),
                ('t_price', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
