# Generated by Django 5.0 on 2024-02-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_coupon_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coupon'),
        ),
    ]
