# Generated by Django 5.0 on 2024-02-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_addcart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
