# Generated by Django 5.0 on 2024-04-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='coupon',
        ),
    ]
