# Generated by Django 5.0 on 2024-04-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_coupon_code_delete_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_total',
        ),
    ]
