# Generated by Django 5.0 on 2024-04-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_vidhi'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidhi',
            name='otp',
            field=models.IntegerField(default=123),
        ),
    ]
