# Generated by Django 5.0 on 2024-04-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_vidhi_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vidhi',
        ),
    ]
