# Generated by Django 5.0 on 2024-07-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_delete_vidhi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_whishlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='add_whishlist',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
