# Generated by Django 5.0 on 2024-07-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
