# Generated by Django 5.0 on 2024-07-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
