# Generated by Django 5.2 on 2025-05-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
