# Generated by Django 5.2 on 2025-05-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_address',
            name='city',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='company_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='country',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='f_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='l_name',
            field=models.TextField(max_length=50),
        ),
    ]
