# Generated by Django 5.2 on 2025-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_billing_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_address',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='f_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='l_name',
            field=models.CharField(max_length=50),
        ),
    ]
